version: "3"
services:
  back_app:
    depends_on:
      - db_postgres
    restart: always
    build: .
    ports:
      - "8080:3000"
    environment:
      - DB_URL=mongodb://db_mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  mongodb:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    container_name: db_postgres
    volumes:
      - postgres:/data/db
    ports:
      - "5432:5432"

volumes:
  mongodata: 